trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/*'

parameters:
- name: runTests
  displayName: Run tests
  type: boolean
  default: true
- name: runOWASPScan
  displayName: Run OWASPScan
  type: boolean
  default: false

- name: sonarqubeInstance
  displayName: 'Select SonarQube for v9.9 or SonarQubeLatest for 10.4'
  type: string
  default: 'SonarQubeLatest'
  values:
  - 'SonarQube'
  - 'SonarQubeLatest'

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/DEV4-development.yaml
  - name: solutionFolder
    value: src
  - name: projectFolder
    value: EPR.Calculator.API
  - name: testProjectFolder
    value: EPR.Calculator.API.UnitTests
  - name: DataFolder
    value: EPR.Calculator.API.Data
  - name: sonarQubeProjectKey
    value: epr-calculator-api
  - name: sonarQubeProjectName
    value: epr-calculator-api
  - name: runNugetTasks
    value: false
  - name: dotnetVersion
    value: dotnetVersion8

resources:
  repositories:
    - repository: CommonTemplates
      name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
      type: git
      ref: feature/automation-tests-pr-hardfail

extends:
  template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
    testProjectFolder: ${{ variables.testProjectFolder }}
    DataFolder: ${{ variables.DataFolder }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{ parameters.runTests }}
    runOWASPScan: ${{ parameters.runOWASPScan }}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    buildMigrationScript: true
    serviceName: $(serviceName)
    sonarqubeInstance: ${{ parameters.sonarqubeInstance }}
    dotnetVersion: ${{ variables.dotnetVersion }}
