trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/*'
      
parameters:

  - name: sonarqubeInstance
    displayName: 'Select SonarQube version'
    type: string
    default: 'SonarQube'
    values:
    - 'SonarQube'
    # - 'SonarQubeLatest'

pool: DEFRA-COMMON-ubuntu2004-SSV5

variables:
  - template: vars/DEV4-development.yaml
  - name: solutionFolder
    value: src
  - name: projectFolder
    value: EPR.Calculator.API
  - name: testProjectFolder
    value: EPR.Calculator.API.UnitTests
  - name: DataFolder
    value: EPR.Calculator.API.Data
  - name: sonarQubeProjectKey
    value: epr-calculator-api
  - name: sonarQubeProjectName
    value: epr-calculator-api
  - name: runNugetTasks
    value: false
  - name: runTests
    value: true
  - name: dotnetVersion
    value: dotnetVersion8

resources:
  repositories:
    - repository: CommonTemplates
      name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
      type: git
      ref: gitleaks-hard-fail-toggleoff

extends:
  template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
    testProjectFolder: ${{ variables.testProjectFolder }}
    DataFolder: ${{ variables.DataFolder }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{ variables.runTests }}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    buildMigrationScript: true
    serviceName: $(serviceName)
    sonarqubeInstance: ${{ parameters.sonarqubeInstance }}
    dotnetVersion: ${{ variables.dotnetVersion }}
