//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.Calculator.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.Calculator.API.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string BillingMessageType {
            get {
                return ResourceManager.GetString("BillingMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob not found for this &apos;{0}&apos; run id to perform requested operation..
        /// </summary>
        public static string BlobNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("BlobNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculator is currently running. You will be able to run another calculation once the current one has finished..
        /// </summary>
        public static string CalculationAlreadyRunning {
            get {
                return ResourceManager.GetString("CalculationAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result csv file metadata not found for this &apos;{0}&apos; run id to perform requested operation..
        /// </summary>
        public static string CsvFileMetadataNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("CsvFileMetadataNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName is required.
        /// </summary>
        public static string FileNameRequired {
            get {
                return ResourceManager.GetString("FileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating billing file for this &apos;{0}&apos; run id already requested..
        /// </summary>
        public static string GenerateBillingFileAlreadyRequest {
            get {
                return ResourceManager.GetString("GenerateBillingFileAlreadyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The financial year is invalid..
        /// </summary>
        public static string InvalidFinancialYear {
            get {
                return ResourceManager.GetString("InvalidFinancialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganisationId is invalid..
        /// </summary>
        public static string InvalidOrganisationId {
            get {
                return ResourceManager.GetString("InvalidOrganisationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunId is invalid..
        /// </summary>
        public static string InvalidRunId {
            get {
                return ResourceManager.GetString("InvalidRunId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run is not having the right status or Is Billing File Generating is already set to true.
        /// </summary>
        public static string InvalidRunStatusForAcceptAll {
            get {
                return ResourceManager.GetString("InvalidRunStatusForAcceptAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Lapcap parameter template should have a count of {0}.
        /// </summary>
        public static string LapcapDataTemplateValuesMissing {
            get {
                return ResourceManager.GetString("LapcapDataTemplateValuesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name should be less than 256 characters.
        /// </summary>
        public static string MaxFileNameLength {
            get {
                return ResourceManager.GetString("MaxFileNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification status is not valid for this &apos;{0}&apos; run id to perform requested operation..
        /// </summary>
        public static string NotAValidClassificationStatus {
            get {
                return ResourceManager.GetString("NotAValidClassificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowAllOrigins.
        /// </summary>
        public static string PolicyName {
            get {
                return ResourceManager.GetString("PolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string ProducerBillingInstructionsDefaultPageNumber {
            get {
                return ResourceManager.GetString("ProducerBillingInstructionsDefaultPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string ProducerBillingInstructionsDefaultPageSize {
            get {
                return ResourceManager.GetString("ProducerBillingInstructionsDefaultPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request accepted for processing..
        /// </summary>
        public static string RequestAcceptedMessage {
            get {
                return ResourceManager.GetString("RequestAcceptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource could not be found..
        /// </summary>
        public static string ResourceNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("ResourceNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ResultMessageType {
            get {
                return ResourceManager.GetString("ResultMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A calculator run with the specified RunId was not found..
        /// </summary>
        public static string RunNotFound {
            get {
                return ResourceManager.GetString("RunNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SASuperUser.
        /// </summary>
        public static string SASuperUserRole {
            get {
                return ResourceManager.GetString("SASuperUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Scheme parameter template should have a count of {0}.
        /// </summary>
        public static string SchemeParameterTemplateValuesMissing {
            get {
                return ResourceManager.GetString("SchemeParameterTemplateValuesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculator.
        /// </summary>
        public static string ServiceBusClientName {
            get {
                return ResourceManager.GetString("ServiceBusClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BADEBT-P,COMC-AL,COMC-FC,COMC-GL,COMC-PC,COMC-PL,COMC-ST,COMC-WD,COMC-OT,COMC-UK,COMC-ENG,COMC-WLS,COMC-SCT,COMC-NIR,LAPC-ENG,LAPC-NIR,LAPC-SCT,LAPC-WLS,LRET-AL,LRET-FC,LRET-GL,LRET-OT,LRET-PC,LRET-PL,LRET-ST,LRET-WD,MATT-AD,MATT-AI,MATT-PD,MATT-PI,SAOC-ENG,SAOC-NIR,SAOC-SCT,SAOC-WLS,SCSC-ENG,SCSC-NIR,SCSC-SCT,SCSC-WLS,TONT-AD,TONT-AI,TONT-PD,TONT-PI.
        /// </summary>
        public static string UniqueReferences {
            get {
                return ResourceManager.GetString("UniqueReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Year is required.
        /// </summary>
        public static string YearRequired {
            get {
                return ResourceManager.GetString("YearRequired", resourceCulture);
            }
        }
    }
}
