<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>86bfd8af-32c6-4de1-869a-572d24c3ea1f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EPR.Calculator.API.UnitTests"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="JetBrains.Annotations"/>
    <Using Include="Microsoft.Extensions.Logging"/>
    <Using Include="System.Collections.Immutable"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.6.0"/>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1"/>
    <PackageReference Include="FluentValidation" Version="12.1.1"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
    <PackageReference Include="JetBrains.Annotations" Version="*" PrivateAssets="All"/>
    <PackageReference Include="Metalama.Framework" Version="2026.1.24" PrivateAssets="All"/>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.14.1"/>
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2"/>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0"/>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0"/>
    <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.18.0"/>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.19"/>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.32.0.713">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0"/>
    <PackageReference Include="Serilog.Expressions" Version="5.0.0"/>
    <PackageReference Include="Serilog.Sinks.Console" Version="6.*"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPR.Calculator.API.Data\EPR.Calculator.API.Data.csproj"/>
    <ProjectReference Include="..\EPR.Calculator.API.BackgroundService\EPR.Calculator.API.BackgroundService.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <SonarQubeSetting Include="sonar.coverage.exclusions">
      <Value>Program*.cs,Options/*.cs,Dtos/*.cs,Constants/*.cs,Models/*.cs</Value>
    </SonarQubeSetting>

    <SonarQubeSetting Include="sonar.cpd.exclusions">
      <Value>**/*.cs</Value>
    </SonarQubeSetting>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CommonResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CommonResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="CommonResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CommonResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
