variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: docker.imageName
  value: eprcalculatorapi
- name: acr.azureContainerRegistryName
  value: prdrwdinfac1401
- name: acr.repositoryName
  value: eprcalculatorapirepository
- name: serviceName
  value: PRDRWDWEBWA1422
- name: kvName
  value: PRDRWDINFKV1401
- name: sqlDBserver
  value: prdrwddbssq1401.database.windows.net
- name: sqlDB
  value: prd1_paycal
- name: acr.Subscription
  value: AZR-RWD-PRD1