variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprcalculatorapi'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprcalculatorapirepository'
  serviceName: 'prdrwdinfcab401'
