variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprcalculatorapi'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprcalculatorapirepository'
  serviceName: 'PRDRWDWEBWA1422'
  kvName: PRDRWDINFKV1401
  sqlDBserver: 'prdrwddbssq1401.database.windows.net'
  sqlDB: 'prd1_paycal'
  acr.Subscription: 'AZR-RWD-PRD1'