<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EPR.Calculator.API.BackgroundService.UnitTests"/>
    <InternalsVisibleTo Include="EPR.Calculator.API.IntegrationTests"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="EPR.Calculator.API.BackgroundService.Telemetry"/>
    <Using Include="JetBrains.Annotations"/>
    <Using Include="Microsoft.Extensions.Logging"/>
    <Using Include="System.Collections.Immutable"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1"/>
    <PackageReference Include="EFCore.BulkExtensions" Version="10.0.1"/>
    <PackageReference Include="FluentValidation" Version="12.1.1"/>
    <PackageReference Include="JetBrains.Annotations" Version="*" PrivateAssets="All"/>
    <PackageReference Include="Metalama.Framework" Version="2026.1.24" PrivateAssets="All"/>
    <PackageReference Include="Microsoft.ApplicationInsights" Version="3.1.2"/>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11"/>
    <PackageReference Include="OpenTelemetry" Version="1.17.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPR.Calculator.API.Data\EPR.Calculator.API.Data.csproj"/>
    <ProjectReference Include="..\EPR.Calculator.API.DataApi\EPR.Calculator.API.DataApi.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <SonarQubeSetting Include="sonar.exclusions">
      <Value>Constants/*.cs,Models/*.cs</Value>
    </SonarQubeSetting>

    <SonarQubeSetting Include="sonar.cpd.exclusions">
      <Value>**/*.cs</Value>
    </SonarQubeSetting>
  </ItemGroup>

</Project>
